imagePullSecrets:
  - name: gh-registry-credential

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: acme-prod
    nginx.ingress.kubernetes.io/auth-url: "https://auth-external.mikroways.net/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth-external.mikroways.net/oauth2/start"
  hosts:
    - host: gitops-workflow.mikroways.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: gitops-workflow-tls
      hosts:
        - gitops-workflow.mikroways.net

resources: 
   limits:
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi
