---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: gitops-workflow
  namespace: gitops-workflow
  labels:
    app: gitops-workflow
resources:
  - helm-release.yaml
  - image-registry.yaml
  - image-policy.yaml
  - image-update-automation.yaml
  - webhook-token.yaml
  - receiver.yaml
configMapGenerator:
  - name: gitops-workflow-values
    files:
      - values.yaml=charts/values-prod.yaml
configurations:
  - kustomizeconfig.yaml
