name: Container Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/nginx
  KUBECONFIG: ./kubeconfig

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - id: image_name
      uses: ASzc/change-string-case-action@v5
      with:
        string: ${{ env.IMAGE_NAME }}
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Lint markdown
      uses: super-linter/super-linter/slim@v5
      env:
        VALIDATE_MD: true
        DEFAULT_BRANCH: main
        MARKDOWN_CONFIG_FILE: markdownlint.yml
        VALIDATE_ALL_CODEBASE: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build container image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.REGISTRY }}/${{ steps.image_name.outputs.lowercase }}
        tags: ${{ github.sha }}
        containerfiles: ./Containerfile

    - name: Push to ghcr.io
      id: push-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up kubeconfig
      run: echo "${{ secrets.KUBECONFIG }}" > ${{ env.KUBECONFIG }}

    - name: Helm Deploy
      run: helm upgrade --install handbook ./charts/gitops-workflow -n gitops-workflow -f .github/deploy/values.yaml --set image.tag=${{ github.sha }} --kubeconfig ${{ env.KUBECONFIG }}
