name: Lint Handbook

on:
  push:
    - main
  pull_request:
    branches:
      - main

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Lint markdown
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_MD: true
          DEFAULT_BRANCH: master
          MARKDOWN_CONFIG_FILE: markdownlint.yml
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
